version: 2
updates:
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/bcmath
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/exif
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/pdo_mysql
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/intl
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/xdebug
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/xsl
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/zip
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/redis
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/gd
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/opcache
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/calendar
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/blackfire
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/sockets
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/soap
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/imap
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/apcu
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/newrelic
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/gmagick
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/igbinary
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./8.1/bullseye/gearman
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/memprof
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/bcmath
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/exif
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/pdo_mysql
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/intl
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/xdebug
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/pcntl
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/zip
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/redis
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/gd
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/meminfo
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/opcache
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/msgpack
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/calendar
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/blackfire
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/sockets
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/soap
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/imap
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/apcu
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/newrelic
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/gmagick
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/igbinary
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./7.4/bullseye/gearman
        schedule:
            interval: daily
        assignees:
            - ro0NL
    -
        package-ecosystem: docker
        directory: ./percona-toolkit
        schedule:
            interval: daily
        assignees:
            - ro0NL
