services:
  - docker

before_install:
  # Update GNU Make to a version that supports output grouping of parallel executed targets
  - |
    ( \
      test -d ~/.make/make-4.1 || \
      ( \
        mkdir -p ~/.make \
        pushd ~/.make && wget http://ftp.gnu.org/gnu/make/make-4.1.tar.gz && \
        tar xvf make-4.1.tar.gz && cd make-4.1 && \
        ./configure && make && popd \
      ) \
    ) && pushd ~/.make/make-4.1 && sudo make install && sudo ln -sf /usr/local/bin/make /usr/bin/make && popd

script:
    - make -j --output-sync=recurse publish

branches:
  only:
    - master

cache:
  directories:
    ~/.make


